/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function add(dateMs: number, duration: DurationInput): number

export declare function addBusinessDays(dateMs: number, amount: number): number

export declare function addDays(dateMs: number, amount: number): number

export declare function addHours(dateMs: number, amount: number): number

export declare function addMilliseconds(dateMs: number, amount: number): number

export declare function addMinutes(dateMs: number, amount: number): number

export declare function addMonths(dateMs: number, amount: number): number

export declare function addQuarters(dateMs: number, amount: number): number

export declare function addSeconds(dateMs: number, amount: number): number

export declare function addWeeks(dateMs: number, amount: number): number

export declare function addYears(dateMs: number, amount: number): number

export declare function areIntervalsOverlapping(leftStart: number, leftEnd: number, rightStart: number, rightEnd: number, inclusive?: boolean | undefined | null): boolean

export declare function clamp(dateMs: number, startMs: number, endMs: number): number

export declare function closestIndexTo(targetMs: number, dates: Array<number>): number | undefined

export declare function closestTo(targetMs: number, dates: Array<number>): number | undefined

export declare function compareAsc(dateLeft: number, dateRight: number): number

export declare function compareDesc(dateLeft: number, dateRight: number): number

export declare function differenceInBusinessDays(laterMs: number, earlierMs: number): number

export declare function differenceInCalendarDays(laterMs: number, earlierMs: number): number

export declare function differenceInDays(aMs: number, bMs: number): number

export declare function differenceInHours(aMs: number, bMs: number): number

export declare function differenceInMilliseconds(aMs: number, bMs: number): number

export declare function differenceInMinutes(aMs: number, bMs: number): number

export declare function differenceInMonths(aMs: number, bMs: number): number

export declare function differenceInQuarters(aMs: number, bMs: number): number

export declare function differenceInSeconds(aMs: number, bMs: number): number

export declare function differenceInWeeks(aMs: number, bMs: number): number

export declare function differenceInYears(aMs: number, bMs: number): number

export interface DurationInput {
  years?: number
  months?: number
  weeks?: number
  days?: number
  hours?: number
  minutes?: number
  seconds?: number
}

export interface DurationParts {
  years: number
  months: number
  days: number
  hours: number
  minutes: number
  seconds: number
}

export declare function eachDayOfInterval(startMs: number, endMs: number, stepOpt?: number | undefined | null): Array<number>

export declare function eachMonthOfInterval(startMs: number, endMs: number, stepOpt?: number | undefined | null): Array<number>

export declare function eachQuarterOfInterval(startMs: number, endMs: number, stepOpt?: number | undefined | null): Array<number>

export declare function eachWeekendOfInterval(startMs: number, endMs: number): Array<number>

export declare function eachWeekOfInterval(startMs: number, endMs: number, options?: object | undefined | null): Array<number>

export declare function eachYearOfInterval(startMs: number, endMs: number, stepOpt?: number | undefined | null): Array<number>

export declare function endOfMonth(dateMs: number): number

export declare function getDaysInMonth(dateMs: number): number

export interface Interval {
  start: number
  end: number
}

export declare function intervalToDailyIntervals(startMs: number, endMs: number): Array<Interval>

export declare function intervalToDuration(startMs: number, endMs: number): DurationParts

export declare function isAfter(date: number, dateToCompare: number): boolean

export declare function isBefore(date: number, dateToCompare: number): boolean

export declare function isEqual(dateLeft: number, dateRight: number): boolean

export declare function isFirstDayOfMonth(dateMs: number): boolean

export declare function isLastDayOfMonth(dateMs: number): boolean

export declare function isSameDay(aMs: number, bMs: number): boolean

export declare function isSameMonth(dateLeftMs: number, dateRightMs: number): boolean

export declare function isSaturday(dateMs: number): boolean

export declare function isSunday(dateMs: number): boolean

export declare function isThisMonth(dateMs: number): boolean

export declare function isWeekend(dateMs: number): boolean

export declare function lastDayOfMonth(dateMs: number): number

export declare function max(dates: Array<number>): number

export declare function min(dates: Array<number>): number

export declare function parseIso(isoString: string): number

export declare function startOfDay(timestamp: number): number

export declare function startOfMonth(dateMs: number): number

export declare function subDays(dateMs: number, amount: number): number

export declare function subHours(dateMs: number, amount: number): number

export declare function subMilliseconds(dateMs: number, amount: number): number

export declare function subMinutes(dateMs: number, amount: number): number

export declare function subMonths(dateMs: number, amount: number): number

export declare function subQuarters(dateMs: number, amount: number): number

export declare function subSeconds(dateMs: number, amount: number): number

export declare function subWeeks(dateMs: number, amount: number): number

export declare function subYears(dateMs: number, amount: number): number
